/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poliventas.comprador;

import Controladores.ArticuloController;
import Observer.Vendedor;
import Modelos.Articulo;
import Observer.Comprador;
import Modelos.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poliventas.articulos.VisualizarArticulo;
import poliventas.vendedor.MenuVendedor;

/**
 *
 * @author usuario
 */
public final class MasBuscados extends javax.swing.JFrame {
    String tipoUsuario;
    Comprador comprador;
    Vendedor vendedor;
    DefaultTableModel modelo = new DefaultTableModel(null, getColumnasE());
    /**
     * Creates new form BusquedaSencilla
     * @param comprador
     */
    public MasBuscados(Comprador comprador) throws SQLException {
        initComponents();
        this.comprador = comprador;
        jLabel4.setText(comprador.getNombres()+" "+comprador.getApellidos());
        tipoUsuario = "comprador";
        setFilas();
        
    }
    public MasBuscados(Vendedor vendedor) throws SQLException {
        initComponents();
        this.vendedor = vendedor;
        jLabel4.setText(vendedor.getNombres()+" "+vendedor.getApellidos());
        tipoUsuario = "vendedor";
        setFilas();
        
    }
    
    public String[] getColumnasE(){
        String columna[] = new String [] {"id","Nombre","Descripcion","Precio"};
        return columna;
    }
    public void setFilas() throws SQLException{
        limpiartabla();
        
        ResultSet consulta= Singleton.Conexion.callProcedure("db_poliventas.masBuscados();");
        Object datos [] = new Object[4];
        while (consulta.next()){
            for(int i=0;i<4;i++){
                datos[i]=consulta.getObject(i+1);                
            }
            modelo.addRow(datos);
        }
        Singleton.Conexion.cerrarConexion();        
    }
    public void  limpiartabla(){

        int a =modelo.getRowCount()-1;
        for(int i=a; i>=0; i--)
            modelo.removeRow(i );
    
    }
    public void visualizarArticulo(){
        int filaseleccionada;
        
        
        filaseleccionada = jTable1.getSelectedRow();
        if (filaseleccionada == -1){
            
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila.");
        } else {
            
            ResultSet busqueda = Singleton.Conexion.callProcedure("obtenerArticulo("+jTable1.getValueAt(filaseleccionada, 0)+");");
            try {
                if(busqueda.next()){
                    
                    ArticuloController.aumentarBusqueda(busqueda);
                    Vendedor vendedorProducto = Controladores.VendedorController.crearVendedor(busqueda);
                    Articulo articulo = Controladores.ArticuloController.crearArticulo(busqueda, vendedor);
                    VisualizarArticulo va;
                    if (tipoUsuario.equals("comprador"))
                        va = new VisualizarArticulo(vendedorProducto, articulo,comprador);
                    else va = new VisualizarArticulo(vendedorProducto, articulo,vendedor);
                    
                    va.setVisible(true);
                    
                    this.dispose();
                }
 
                
            } catch (SQLException ex) {
                Logger.getLogger(MasBuscados.class.getName()).log(Level.SEVERE, null, ex);
            }
            Singleton.Conexion.cerrarConexion();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 244, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Mas Buscados");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salida.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Detalles Articulo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(333, 333, 333))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(85, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (tipoUsuario.equals("comprador")){
            MenuComprador ingreso = new MenuComprador(comprador);
            ingreso.setVisible(true);
            this.dispose();
        }
        else{
            MenuVendedor ingreso = new MenuVendedor(vendedor);
            ingreso.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        visualizarArticulo();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
