/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poliventas;

import Observer.Comprador;
import Observer.Vendedor;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Pendientes extends javax.swing.JFrame {
    String tipoUsuario;
    Comprador comprador;
    Vendedor vendedor;
    String tipoConsulta;
    
    DefaultTableModel modelo;
    /**
     * Creates new form Pendientes
     * @param comprador
     */
    public Pendientes(Comprador comprador) {
        initComponents();
        tipoConsulta="compras";
        tipoUsuario ="comprador";
        this.comprador = comprador;
        modelo = new DefaultTableModel(null, getColumnasC());
    }
    public Pendientes(Vendedor vendedor, String tipo) {
        initComponents();
        tipoConsulta=tipo;
        tipoUsuario ="vendedor";
        this.vendedor = vendedor;
        if (tipo.equals("ventas"))
            modelo = new DefaultTableModel(null, getColumnasV());
        else
            modelo = new DefaultTableModel(null, getColumnasC());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 244, 244));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Tipo de Pendiente");

        jTable2.setModel(modelo);
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Detalles");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton3)))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public String[] getColumnasC(){
        String columna[] = new String [] {"id","Compra","Fecha","Total","Estado"};
        return columna;
    }
    public String[] getColumnasV(){
        String columna[] = new String [] {"id","Venta","Fecha","Total","Estado"};
        return columna;
    }
    public void setFilas() throws SQLException{
        limpiartabla();
        
        ResultSet consulta;
        if (tipoUsuario.equals("comprador"))
            consulta= Singleton.Conexion.callProcedure("db_poliventas.compras('"+comprador.getCedula()+"');");
        else{
            if(tipoConsulta.equals("ventas"))
                consulta= Singleton.Conexion.callProcedure("db_poliventas.ventas('"+vendedor.getCedula()+"');");
            else
                consulta= Singleton.Conexion.callProcedure("db_poliventas.compras('"+vendedor.getCedula()+"');");
        }
        Object datos [] = new Object[4];
        while (consulta.next()){
            for(int i=0;i<5;i++){
                datos[i]=consulta.getObject(i+1);                
            }
            modelo.addRow(datos);
        }
        Singleton.Conexion.cerrarConexion();        
    }
    public void  limpiartabla(){

        int a =modelo.getRowCount()-1;
        for(int i=a; i>=0; i--)
            modelo.removeRow(i );
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
